{
 "title": "proxy layer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Client Request traffic",
   "type": "graph",
   "description": "http traffic out and in (kbytes)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_in_kbytes_total[5m])",
     "legendFormat": "HTTP traffic in"
    },
    {
     "expr": "rate(squid_client_http_kbytes_out_kbytes_total[5m])",
     "legendFormat": "HTTP traffic out"
    }
   ]
  },
  {
   "title": "Services Up",
   "type": "stat",
   "description": "Percent of squid proxy reporting healthy over deployment replica count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(squid_up) / count(kube_deployment_spec_replicas{deployment=\"cannedsquid\"})",
     "legendFormat": "services up"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "client errors over client requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_errors_total / squid_client_http_requests_total",
     "legendFormat": "client_http"
    }
   ]
  }
 ]
}