{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cannedSquid.fullname" . }}
  labels:
    {{- include "cannedSquid.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cannedSquid.selectorLabels" . | nindent 4 }}
{{- end }}
